"use client";

import { Badge } from "@/components/ui/badge";
import { formatCurrency } from "@/lib/utils";
import type { Receipt } from "@/types";

export function ReceiptDocument({
  receipt,
  id = "receipt-print-root",
}: {
  receipt: Receipt;
  id?: string;
}) {
  return (
    <div
      id={id}
      className="rounded-2xl border border-slate-200 bg-white p-6 text-slate-900 shadow-sm sm:p-8 dark:border-slate-700 dark:bg-slate-900 dark:text-slate-100"
    >
      <div className="flex flex-wrap items-start justify-between gap-4 border-b border-emerald-100 pb-5 dark:border-emerald-900">
        <div>
          <p className="text-xs font-semibold uppercase tracking-wider text-emerald-600">
            Payment Receipt
          </p>
          <h1 className="mt-1 text-2xl font-bold">{receipt.societyName}</h1>
          <p className="mt-1 text-sm text-slate-500">
            Flat {receipt.wing}-{receipt.flatNo} · {receipt.ownerName}
          </p>
        </div>
        <div className="text-right">
          <p className="text-lg font-bold text-emerald-600">{receipt.receiptNo}</p>
          <Badge variant="success" className="mt-2">
            Paid
          </Badge>
          <p className="mt-2 text-xs text-slate-500">Date: {receipt.paymentDate}</p>
        </div>
      </div>

      <div className="mt-6 grid gap-3 text-sm sm:grid-cols-2">
        <div className="flex justify-between rounded-xl bg-slate-50 px-4 py-3 dark:bg-slate-800/60 sm:block">
          <p className="text-xs text-slate-400">Invoice</p>
          <p className="font-semibold">{receipt.invoiceNo}</p>
        </div>
        <div className="flex justify-between rounded-xl bg-slate-50 px-4 py-3 dark:bg-slate-800/60 sm:block">
          <p className="text-xs text-slate-400">Payment mode</p>
          <p className="font-semibold">{receipt.paymentMode}</p>
        </div>
        <div className="flex justify-between rounded-xl bg-slate-50 px-4 py-3 dark:bg-slate-800/60 sm:block">
          <p className="text-xs text-slate-400">UTR / Transaction ID</p>
          <p className="font-semibold">{receipt.utr}</p>
        </div>
        <div className="flex justify-between rounded-xl bg-slate-50 px-4 py-3 dark:bg-slate-800/60 sm:block">
          <p className="text-xs text-slate-400">Bank</p>
          <p className="font-semibold">{receipt.bank}</p>
        </div>
      </div>

      <div className="mt-6 rounded-2xl bg-emerald-50 p-5 dark:bg-emerald-950/30">
        <p className="text-xs font-semibold uppercase text-emerald-700 dark:text-emerald-300">
          Amount received
        </p>
        <p className="mt-1 text-3xl font-bold text-emerald-700 dark:text-emerald-300">
          {formatCurrency(receipt.totalPaid)}
        </p>
        {receipt.lateFee > 0 && (
          <p className="mt-1 text-xs text-slate-500">
            Includes late fee {formatCurrency(receipt.lateFee)}
          </p>
        )}
      </div>

      <p className="mt-6 text-xs text-slate-400">
        Collected by {receipt.collectedBy} · Month {receipt.month}
      </p>
      <p className="mt-1 text-[11px] text-slate-400">
        Generated by SocietyOne · Computer-generated receipt.
      </p>
    </div>
  );
}
